name: 'MarcusMcGowan '
favicon: null
layout_spectrum: 0.29024
typography_spectrum: 0.6753225391730666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#363636'
    - '#656565'
    - '#ffffff'
    - '#9b3919'
  brandStrength: 0.053778845351189375
  lightness: 0.6944686435163021
  saturation: 0.0926733601372689
  rhythmicContrast: 0.9703356984537095
purpose: []
