favicon: null
name: 'MarcusMcGowan '
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.05197133
  brandStrength: 0
  lightness: 0.9767025
  brandColors:
    - '#2d2d2d'
    - '#fefefe'
    - '#d1d1d1'
    - '#9a9a9a'
    - '#717171'
  rhythmicContrast: 0.9703357
typography_spectrum: 0.6753225391730666
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.35586
analytics:
  twitter: null
  google: null
  facebook: null
