name: 'MarcusMcGowan '
favicon: null
layout_spectrum: 0.35586
typography_spectrum: 0.6753225391730666
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2d'
    - '#fefefe'
    - '#d1d1d1'
    - '#9a9a9a'
    - '#717171'
  brandStrength: 0
  lightness: 0.9767025
  saturation: 0.05555556
  rhythmicContrast: 0
purpose: []
